### ISSUE TITLE
Bug: the character's name plate covers the hit point field

### ISSUE THREAD

**Issue by ckdragons** [xaukael/covered-token-rescue-hud#13] opened 2023-03-25 06:43 UTC
![image](https://user-images.githubusercontent.com/84493092/227701568-b916cc06-e34f-4055-b58d-fe158e377266.png)

**Comment by xaukael** [comment] 2023-03-27 12:41
I am not sure how you managed that, but I cannot reproduce. Can you describe the steps to make this happen?

**Comment by ckdragons** [comment] 2023-03-27 14:54
Right-clicked on the hidden token's icon to bring up the HUD. In the picture, the icon showing is for Nora (PC) and Chumley (PC) is hidden underneath.

**Comment by xaukael** [comment] 2023-07-14 00:59
fixed by removing the tooltip

**Closed as completed by xaukael** 2023-07-14 00:59 UTC
